### PR TITLE
Updates for Django 1.8 support

### PR DESCRIPTION
**Pull request by PetrDlouhy**

### CODE REVIEW

**Comment by varche1** [comment]
PetrDlouhy, thanks for the pull request. Could you fix tests?

**Comment by PetrDlouhy** [comment]
@varche1: The tests for Django 1.6 (only tested previously) completes successfully. I expand tests by TOX testing of another Django versions, for which the tests are failing. This was intentional, this must have to be fixed before pulling the request.

Unfortunately, I bumped into problems with Django 1.7, which I couldn't solve easily. If there are some extra positional parameters for custom model fields, the migrations throw TypeError as written in [docs](http://django.readthedocs.org/en/latest/topics/migrations.html#custom-fields). I wasn't able to rewrite this to be backward compatible and working.

I would try to solve it, but any help would be appreciated.

**Comment by PetrDlouhy** [comment]
@varche1 I finally managed to make Django denorm tests pass in all desired environments. It is tested in from Django 1.5 to Django 1.8 and in several Python versions with all supported databases.

Django 1.9 and master is tested with negative result, but it is ignored. The fixing is waiting for somebody more determined.

Now this is ready for pull.

**Comment by PetrDlouhy** [comment]
These and other compatibility fixes are now part of devel branch in django-devel repository. So if you wish, pull it from there. Closing this PR.

**Pull request closed without merging**
